package general;

/**
 * Provides a method to get a double from a random or deterministic number generator.
 * 
 */
public interface INumberGenerator {

	/**
	 * @return the double generated by this method
	 */
	double getNumber();
}
